spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/springboot-login
    password: 1234
##配置mapper的xml文件的路径
mybatis:
  mapper-locations: classpath:mybatis/*.xml
shiro:
  ##当用户访问某个需要登录的功能时，但是被shiro内置的过滤器拦截后，判断本次请求
  ##没有登录，而是直接访问的，则重定向到loginUrl的路径资源响应给用户
  loginUrl: /login